---
title: "Tables main"
format:
  docx:
    reference-doc: reference-doc.docx
    fig-cap-location: top
execute:
  echo: false
crossref:
  fig-title: '**Figure S**'
  fig-labels: arabic
  title-delim: "**.**"
lof: TRUE
---

```{r, warning=FALSE, results='hide', cache.comments=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(flextable)
library(survival)
library(ggplot2)
library(ggfortify)
library(survminer)
library(ggh4x)
library(officer)
library(knitr)
library(officedown)

knitr::opts_chunk$set(
  echo       = FALSE,
  message    = FALSE,
  warning    = FALSE
)
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE, tab.cap.pre = "Table ", tab.cap.sep = ": ")
num_tab <- 1
num_fig <- 1
```

```{r, warning=FALSE, results='hide', cache.comments=FALSE, message=FALSE}
source(here("functions_lc.R"))
```

```{r, warning=FALSE, results='hide', cache.comments=FALSE, message=FALSE}
source(here("prep_data_lc.R"))
```


```{r, warning=FALSE, cache.comments=FALSE, message=FALSE, results='asis'}
# Table One VE ----
captions_ve <- captions %>% filter(!cve)
for (ii in 1) {

    cat("\n") 
    cat("##",paste0("**Table S", num_tab, ": ", captions_ve$caption_w_1[ii], "**", captions_ve$caption_2[ii]))
    tbl_char <- table_characteristics_weighted %>%
      filter(exposure_name == captions_ve$exposure_name[ii]) %>%
      filter(comparator_name == captions_ve$comparator_name[ii]) %>%
      filter(cdm_name == captions_ve$cdm_name[ii])

    flextable_to_rmd(
      getTableOne(tbl_char, captions_ve$cve[ii])
    )
    cat("UV = unvaccinated, V = vaccinated, ASMD = absolute standardized mean difference")
    
    cat("\n\n\\pagebreak\n")
    num_tab <- num_tab + 1
}
```

```{r, warning=FALSE, cache.comments=FALSE, message=FALSE, results='asis'}
# Table Outcome ----

for (ii in 1) {
if (captions_outcome$cve[ii]) {
  tbl_outcome <- estimates %>%
    filter(outcome_name %in% c(captions_outcome$outcome_name[ii]), "next_covid") %>%
    filter(exposure_name == captions_outcome$exposure_name[ii]) %>%
    filter(comparator_name == captions_outcome$comparator_name[ii]) %>%
    filter(censoring_method == captions_outcome$censoring_method[ii]) %>%
    mutate(study = paste0("Cohort ", study)) %>%
    filter(cdm_name != "CORIVA") %>%
    select(-c("coef","hr","se_coef","z","p", "lower_hr", "upper_hr", "model", "adjustment", "censoring_method", "covariates", "comparison_id", "outcome_group", "exposure_cohort_id", "exposure_name",          "comparator_cohort_id", "comparator_name",     "skip", "variable")) %>%
    mutate(study = paste0("Cohort", study),
           outcome_name = if_else(
             outcome_name == "next_covid",
             "C",
             "LC"
           )) %>%
    distinct() %>%
    pivot_wider(names_from = c(outcome_name), 
                values_from = c(number_events_exposure, number_events_comparator)) %>%
    mutate(
      number_events_exposure_LC = nice_perc(number_events_exposure_LC, number_events_exposure_C, dec = 2),
      number_events_comparator_LC = nice_perc(number_events_comparator_LC, number_events_comparator_C, dec = 2),
      number_events_exposure_C = nice(number_events_exposure_C),
      number_events_comparator_C = nice(number_events_comparator_C)
    ) %>%
     select("Database name" = "cdm_name",
         "Staggered cohort" = "study",
         "BNT162b2_Individuals (N)" = "number_exposures",
         "BNT162b2_COVID-19 (N)" = "number_events_exposure_C",
         "BNT162b2_LongCOVID-19 (N (%))" = "number_events_exposure_LC",
         "ChAdOx1_Individuals (N)" = "number_comparators",
         "ChAdOx1_COVID-19 (N)" = "number_events_comparator_C",
         "ChAdOx1_LongCOVID-19 (N (%))" = "number_events_comparator_LC")
} else {
  tbl_outcome <- estimates %>%
  filter(outcome_name %in% c(captions_outcome$outcome_name[ii], "next_covid")) %>%
  filter(exposure_name == captions_outcome$exposure_name[ii]) %>%
  filter(comparator_name == captions_outcome$comparator_name[ii]) %>%
  filter(censoring_method == captions_outcome$censoring_method[ii]) %>%
    select(-c("coef","hr","se_coef","z","p", "lower_hr", "upper_hr", "model", "adjustment", "censoring_method", "covariates", "comparison_id", "outcome_group", "exposure_cohort_id", "exposure_name",          "comparator_cohort_id", "comparator_name",     "skip", "variable")) %>%
  mutate(study = paste0("Cohort", study),
         outcome_name = if_else(
           outcome_name == "next_covid",
           "C",
           "LC"
         )) %>%
    distinct() %>%
    pivot_wider(names_from = c(outcome_name), 
                values_from = c(number_events_exposure, number_events_comparator)) %>%
    mutate(
      number_events_exposure_LC = nice_perc(number_events_exposure_LC, number_events_exposure_C, dec = 2),
      number_events_comparator_LC = nice_perc(number_events_comparator_LC, number_events_comparator_C, dec = 2),
      number_events_exposure_C = nice(number_events_exposure_C),
      number_events_comparator_C = nice(number_events_comparator_C)
    ) %>%
  select("Database name" = "cdm_name",
         "Staggered cohort" = "study",
         "Vaccinated_Individuals (N)" = "number_exposures",
         "Vaccinated_COVID-19 (N)" = "number_events_exposure_C",
         "Vaccinated_LongCOVID-19 (N (%))" = "number_events_exposure_LC",
         "Unvaccinated_Individuals (N)" = "number_comparators",
         "Unvaccinated_COVID-19 (N)" = "number_events_comparator_C",
         "Unvaccinated_LongCOVID-19 (N (%))" = "number_events_comparator_LC") 
}

  
  

if(captions_outcome$exposure_name[ii] == "astrazeneca vaccinated") {
  tbl_outcome <- tbl_outcome %>%
    filter(`Database name` != "CORIVA")
}

  if(captions_outcome$outcome_name[ii] %in% c("longcovid_post_acute_covid19_90_365", "next_post_acute_covid19")) {
    tbl_outcome <- tbl_outcome %>%
    filter(`Database name` != "CORIVA") %>%
      filter(`Database name` != "GOLD")
    if (captions_outcome$cve[ii]) {
      tbl_outcome <- NULL
    }
  }


  if (!is.null(tbl_outcome)) {
    cat("\n") 
    cat("##", paste0("**Table S", num_tab, ": ", captions_outcome$caption_1[ii], "**", captions_outcome$caption_2[ii]))
  flextable_to_rmd(
    tbl_outcome %>%
      as_grouped_data(groups = c("Database name")) %>%
      flextable() %>%
      separate_header() %>%
      hline(border = border) %>%
      set_table_properties(width = 1, layout = "autofit") %>%
      bold(part = "header") %>%
      bold(j = 1, part = "body") %>%
      bg(j = seq(2, ncol(tbl_outcome), 2), bg = "#ededed") %>%
      fontsize(size = 9, part = "header") %>%
      fontsize(size = 8, part = "body")  %>%
      padding(padding = 1, part = "all") %>%
      align(align = "center", part = "header") %>%
      align(align = "left", part = "body")
  )

cat("\n\n\\pagebreak\n")
num_tab <- num_tab + 1

}

}
```